In [1]:
import hazm
import pandas as pd
from lxml import etree
from pathlib import Path
import os
from tqdm import tqdm
tqdm.pandas()
import matplotlib.pyplot as plt
import numpy as np
import gensim
import warnings
import joblib
warnings.filterwarnings('ignore')

/home/fazel/anaconda3/envs/nlp_thesis/lib/python3.7/site-packages/tqdm/std.py:648: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel


دانش جغرافي دانش آموزان امريكايي در 
پايين ترين سطح جهاني است 

. واحد رسانه هاي خارجي: دنيا، دنياي بزرگي است و به ياد داشتن نام 
 اماكن، نقاط و چيزهاي مختلف آن كار آساني نيست. كارشناسان علوم 
آموزش امريكا مي خواهند اهميت جغرافيا را به دانش آموزان گوشزد و آنان 
را به تقويت دانش خود در اين زمينه تشويق كنند. 
به گزارش تلويزيون آزمونهاي سي ان ان، گوناگوني كه در موردويژگيهاي 
جغرافيايي جهان ياحتي امريكا از دانش آموزان اين كشور شده است، 
نتايج قابل توجهي دربرداشته است. مثلا بيشتر دانش آموزان دوره 
راهنمايي امريكا نمي دانند درياچه هاي كوچك از عمده ويژگيهاي ايالت 

In [4]:
label_encoder = joblib.load('/home/fazel/env/thesis/label_encoder.joblib')


In [10]:
## To create train_test_split
# from sklearn.preprocessing import LabelEncoder


# # Labels of data to numbers
# label_encoder = joblib.load('/home/fazel/env/thesis/label_encoder.joblib')
# # Hamshahri Dataset, News text and labels
# df = pd.read_json('/home/fazel/env/thesis/hamshahri_df.json')
# df['cat_english'] = label_encoder.transform(df['cat_english'])

# import gc;gc.collect()

# df

In [8]:
# print(" ".join(df.text[0]))

جاودانگی در زندگی گروهی از طریق هنر نگاهی به نمایشگاه آثار هنری احمد طباطبایی موضوع آثار طباطبایی مورچگان هستند ولی در باطن چنین ظاهری ، این انسانهاهستند که در هیبتی حشره گونه در تابلوهای نقاشی نمایشگر گوشه هایی از زندگی خود هستند . مورچه\u200cای را دیده\u200cایم که بار سنگین خودرا به دوش می\u200cکشد و در بین راه خسته می\u200cشود یا در نتیجه پیش آمدن یک حادثه اتفاقی بار از دستش رها شده و برای گریز از خطر آن را می\u200cگذارد و فرار می\u200cکند . اما ساعتی بعد به همان نقطه برمی گردد و بار را دوباره به دوش کشیده نفس زنان و عرق ریزان آن را به منزل او می\u200cرساند می\u200cداند که اگر در میان راه از بین رفت ، یک مورچه دیگر با همان استعداد غریزه عملی را که او شروع کرده به پایان می\u200cرساند . پس او می\u200cداند که بعد از خودش نسل آینده\u200cای وجود دارد که باید از مزایای آن استفاده نماید . چه داستان درازی ، انتها و پایانی هم میلیونها ندارد سال گذشته ، میلیاردها سال دیگر خواهد_گذشت وهمین برنامه میلیونها بار دیگر تجدید می\u200cشود . پس باید گفت سیر حیات و تکامل پایان ناپذیر است . اسرار جهان پ

In [9]:
## Code to create it from hamshahri_df.json
# from sklearn.model_selection import train_test_split

# tokens_train, tokens_test,\
#     label_train, label_test = train_test_split(df['text'], 
#                                               df['cat_english'],
#                                               random_state=43)

# del df

# import gc;gc.collect()

# joblib.dump(tokens_train, 'tokens_train.joblib.gz', compress=5)

# joblib.dump(tokens_test, 'tokens_test.joblib.gz', compress=5)

# joblib.dump(label_test, 'label_test.joblib.gz', compress=5)

# joblib.dump(label_train, 'label_train.joblib.gz', compress=5)

In [6]:
import joblib
tokens_train = joblib.load('tokens_train.joblib.gz')

In [7]:
import gc;gc.collect()

20

In [8]:
tokens_test = joblib.load('tokens_test.joblib.gz')

In [9]:
gc.collect()

20

In [10]:
label_test = joblib.load('label_test.joblib.gz')

In [11]:
label_train = joblib.load('label_train.joblib.gz')

In [12]:
gc.collect()

60

In [223]:
count = 0
for i in tokens_train:
    if ":" in i:
        count += 1
        print(' '.join(i[:50]))
        print('===========')
    if count > 20:
        break
        

بحث آزاد در نشست انجمن هنرمندان سفالگر انجمن هنرمندان سفالگر در ادامه برگزاری جلسات بحث و بررسی پیرامون سفالگری ایران ، جلسه دیگری را در روز سه شنبه ۲۹ تیرماه از ساعت ۱۵ تا ۱۷ در فرهنگسرای نیاوران برگزار می\u200cکند . عنوان این جلسه ، بحث آزاد است و تمامی
در بخشنامه وزیر آموزش و طرح هدیه به پرورش اعلام شد مدرسه در سراسر کشور به اجرا درمی آید گروه علمی فرهنگی : شیوه نامه جذب کمک\u200cهای مردمی اولیاء در قالب طرح هدیه به مدرسه در سال تحصیلی ۷۸۷۷ برای اجرا در مدارس کشور اعم ازدولتی و غیرانتفاعی تدوین شد
نقشه آسمان شب زمستان خوانندگانی که نامشان در ادامه می\u200cآید برای دریافت نقشه آسمان شب زمستان نامه نوشته_بودند . متاسفانه تعداد تقاضاهای رسیده از حد تصور ما بیرون بود و موجودی نقشه\u200cهای ما کفاف نداد و به بسیاری نرسید . از کسانی که نامه نوشتند و ستون آسمان شب را
ناسازگاری حکومت\u200cهای دولت سالار با راهبردهای توسعه کارکردهای نظام سیاسی در فرایند توسعه در گفت وگو با دکتر حسین عظیمی بخش دوم اشاره : در بخش اول این گفت وگو ابتدا رابطه نظام سیاسی با مسائل اقتصادی بررسی در شد این باره دکتر

### Feature engineering 

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
tfidf = TfidfVectorizer?

In [48]:
tfidf = TfidfVectorizer(lowercase=False,
                        tokenizer=lambda x: x,
                        smooth_idf=False,
                        max_df=3000,
                        min_df=50,
                       )

In [49]:
X_train = tfidf.fit_transform(tqdm(tokens_train))

100%|██████████| 125080/125080 [00:16<00:00, 7581.50it/s]


In [83]:
X_train

<125080x22685 sparse matrix of type '<class 'numpy.float64'>'
	with 8420086 stored elements in Compressed Sparse Row format>

In [84]:
X_test = tfidf.transform(tqdm(tokens_test))

100%|██████████| 41694/41694 [00:06<00:00, 6257.64it/s]


In [85]:
X_test

<41694x22685 sparse matrix of type '<class 'numpy.float64'>'
	with 2807380 stored elements in Compressed Sparse Row format>

In [86]:
print(" ".join(tfidf.inverse_transform(X_train[0])[0]))

پارک ضلع پاسداران انتهای اعم نیاوران فرهنگسرای تیرماه ۲۹ سفالگری جلسات هنرمندان


### Learning

In [21]:
from sklearn.linear_model import LogisticRegression

In [133]:
LogisticRegression?

In [134]:
lr = LogisticRegression(max_iter=1000, multi_class='multinomial', verbose=True,)

In [149]:
lr = LogisticRegression(max_iter=1000,multi_class='multinomial', solver='sag', verbose=True,)

In [150]:
%time lr.fit(X_train, label_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


convergence after 23 epochs took 19 seconds
CPU times: user 19.6 s, sys: 15 µs, total: 19.6 s
Wall time: 19.6 s


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   19.6s finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=True,
                   warm_start=False)

In [151]:
lr.score(X_train, label_train)

0.848512951710905

In [152]:
print('Precision on Test Set: ', lr.score(X_test, label_test))

Precision on Test Set:  0.8007147311363746


In [31]:
from sklearn.metrics import classification_report, confusion_matrix,\
    f1_score
def eval_results(y_true, y_pred):
    print(classification_report(y_true, y_pred,\
                          target_names=label_encoder.classes_))
    print(confusion_matrix(y_true, y_pred))
    print(f1_score(y_true, y_pred, average='weighted'))


In [154]:
eval_results(label_test, lr.predict(X_test))

                     precision    recall  f1-score   support

            Economy       0.86      0.83      0.84      5892
 Literature and Art       0.74      0.59      0.66      1621
      Miscellaneous       0.78      0.89      0.83     19272
Natural Environment       0.48      0.12      0.19       233
           Politics       0.80      0.71      0.75      4884
Science and Culture       0.70      0.57      0.63      3383
             Social       0.73      0.52      0.61      2373
              Sport       0.98      0.95      0.96      3925
            Tourism       0.71      0.27      0.39       111

           accuracy                           0.80     41694
          macro avg       0.75      0.60      0.65     41694
       weighted avg       0.80      0.80      0.79     41694

[[ 4866     1   852     0   111    33    19     5     5]
 [    5   962   560     0     2    77    11     4     0]
 [  489   239 17153    17   531   530   260    50     3]
 [    7     1   179    27     1  

In [155]:
label_encoder.inverse_transform(lr.predict(tfidf.transform([['پرسپولیس']])))

array(['Sport'], dtype=object)

In [156]:
label_encoder.inverse_transform(lr.predict(tfidf.transform([['پیروزی']])))

array(['Miscellaneous'], dtype=object)

In [157]:
label_encoder.inverse_transform(lr.predict(tfidf.transform([[ 'نویسنده']])))

array(['Miscellaneous'], dtype=object)

In [158]:
tfidf.transform([[ 'مس']])

<1x22685 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [123]:
word_test = tfidf.transform([['شیر']])

In [124]:
word_test.argmax()

11128

In [181]:
def pred_classes(tokens):
    probas = list(
        zip(
            range(9),
            *lr.predict_proba(
                            tfidf.transform([tokens])
            )
        )
    )
    for i, j in probas: print(label_encoder.\
                              inverse_transform([i]),
                              " : ", "{:.3}".format(j*100),
                              '%')

In [180]:
pred_classes(['پرسپولیس'])

['Economy']  :  2.44 %
['Literature and Art']  :  0.465 %
['Miscellaneous']  :  2.39 %
['Natural Environment']  :  0.161 %
['Politics']  :  0.969 %
['Science and Culture']  :  1.05 %
['Social']  :  1.03 %
['Sport']  :  91.4 %
['Tourism']  :  0.0758 %


In [203]:
pred_classes(['نقاش' ])

['Economy']  :  5.09 %
['Literature and Art']  :  27.6 %
['Miscellaneous']  :  57.5 %
['Natural Environment']  :  0.418 %
['Politics']  :  3.25 %
['Science and Culture']  :  1.95 %
['Social']  :  2.11 %
['Sport']  :  1.88 %
['Tourism']  :  0.185 %


In [210]:
list(zip(range(len(label_train)), label_encoder.inverse_transform(label_train)))[:50]

[(0, 'Miscellaneous'),
 (1, 'Science and Culture'),
 (2, 'Science and Culture'),
 (3, 'Miscellaneous'),
 (4, 'Science and Culture'),
 (5, 'Miscellaneous'),
 (6, 'Sport'),
 (7, 'Miscellaneous'),
 (8, 'Miscellaneous'),
 (9, 'Politics'),
 (10, 'Literature and Art'),
 (11, 'Miscellaneous'),
 (12, 'Economy'),
 (13, 'Miscellaneous'),
 (14, 'Politics'),
 (15, 'Miscellaneous'),
 (16, 'Politics'),
 (17, 'Science and Culture'),
 (18, 'Economy'),
 (19, 'Literature and Art'),
 (20, 'Economy'),
 (21, 'Miscellaneous'),
 (22, 'Sport'),
 (23, 'Economy'),
 (24, 'Economy'),
 (25, 'Science and Culture'),
 (26, 'Miscellaneous'),
 (27, 'Sport'),
 (28, 'Miscellaneous'),
 (29, 'Social'),
 (30, 'Economy'),
 (31, 'Miscellaneous'),
 (32, 'Economy'),
 (33, 'Miscellaneous'),
 (34, 'Miscellaneous'),
 (35, 'Miscellaneous'),
 (36, 'Politics'),
 (37, 'Economy'),
 (38, 'Miscellaneous'),
 (39, 'Miscellaneous'),
 (40, 'Miscellaneous'),
 (41, 'Politics'),
 (42, 'Miscellaneous'),
 (43, 'Sport'),
 (44, 'Social'),
 (45, 'Mi

In [122]:
lr.coef_[0][14586]

1.0003273274507736

In [219]:
count = 0
for i in tokens_train:
    if ":" in i:
        count += 1
        print(i)
    if count > 20:
        break
        

['بحث', 'آزاد', 'در', 'نشست', 'انجمن', 'هنرمندان', 'سفالگر', 'انجمن', 'هنرمندان', 'سفالگر', 'در', 'ادامه', 'برگزاری', 'جلسات', 'بحث', 'و', 'بررسی', 'پیرامون', 'سفالگری', 'ایران', '،', 'جلسه', 'دیگری', 'را', 'در', 'روز', 'سه', 'شنبه', '۲۹', 'تیرماه', 'از', 'ساعت', '۱۵', 'تا', '۱۷', 'در', 'فرهنگسرای', 'نیاوران', 'برگزار', 'می\\u200cکند', '.', 'عنوان', 'این', 'جلسه', '،', 'بحث', 'آزاد', 'است', 'و', 'تمامی', 'علاقه', 'مندان', 'اعم', 'از', 'دانشجویان', 'و', 'هنرمندان', 'می\\u200cتوانند', 'در', 'آن', 'شرکت', 'کنند', '.', 'نشانی', ':', 'انتهای', 'خیابان', 'پاسداران', '،', 'ضلع', 'غربی', 'پارک', 'نیاوران', '.']
['در', 'بخشنامه', 'وزیر', 'آموزش', 'و', 'طرح', 'هدیه', 'به', 'پرورش', 'اعلام', 'شد', 'مدرسه', 'در', 'سراسر', 'کشور', 'به', 'اجرا', 'درمی', 'آید', 'گروه', 'علمی', 'فرهنگی', ':', 'شیوه', 'نامه', 'جذب', 'کمک\\u200cهای', 'مردمی', 'اولیاء', 'در', 'قالب', 'طرح', 'هدیه', 'به', 'مدرسه', 'در', 'سال', 'تحصیلی', '۷۸۷۷', 'برای', 'اجرا', 'در', 'مدارس', 'کشور', 'اعم', 'ازدولتی', 'و', 'غیرانتفاعی', 'ت

In [216]:
count

98595

In [70]:
tfidf.get_feature_names()[2001]

'امیری'

In [71]:
for j in range(9):
    print(label_encoder.classes_[j])
    for i in lr.coef_[j].argsort()[-10:][::-1]:
        print (tfidf.get_feature_names()[i], "  coef: ", lr.coef_[j][i])
    print('Words with the most Negative Effect: ')
    for i in lr.coef_[j].argsort()[:3]:
        print (tfidf.get_feature_names()[i], "  coef: ", lr.coef_[j][i])
    print('===================')


Economy
نکته\u200cها   coef:  7.442496074108143
مسوولان   coef:  5.760101798182887
پارسال   coef:  5.602589934262603
جنان   coef:  5.508345825088189
مسوول   coef:  5.414654198854963
مثقال   coef:  5.247329777366754
ستد   coef:  5.091769265951231
دادوستد   coef:  5.085798092669646
اوپک   coef:  5.043192036967042
گذاری\u200cهای   coef:  4.922812267943668
Words with the most Negative Effect: 
سنندج   coef:  -3.6479055195935497
ناطق   coef:  -3.4819080268591223
اذان   coef:  -3.181028309532249
Literature and Art
نقاش   coef:  4.967871733480061
تئاتری   coef:  4.71874468909102
آثارش   coef:  4.475377988086324
بیننده   coef:  4.211805222078013
/تا   coef:  4.150480928917235
نمایشنامه   coef:  4.076598786964643
گالری   coef:  4.053650113401888
فیلمساز   coef:  3.922951580172431
فیلمبرداری   coef:  3.9106712857149826
جشنواره\u200cهای   coef:  3.834998667012885
Words with the most Negative Effect: 
قرآنی   coef:  -2.025272706194635
تقاطع   coef:  -2.011963140912307
پرسپولیس   coef:  -1.73893589

## Tokenize and make ready examples

In [302]:
sample1 = """
به گزارش همشهریآنلاین به نقل از شرق،  «در بعضی جاها اختیار رئیس‌جمهور از اختیار یک شهروند عادی کمتر است... لوایح دوگانه حداقل‌هایی است که باید باشد... بدون رعایت روح لوایح، دیگر رئیس‌جمهور خیلی کاره‌ای نیست». این جملات سیدمحمد خاتمی در روزهایی بیان شد که لوایح دوگانه پیشنهادی‌اش بین شورای نگهبان و مجلس در رفت‌وآمد بود؛ لوایحی که به اعتقاد برخی از صاحب‌نظران برای اجرای قانون اساسی و رعایت حقوق ملت لازم و ضروری بود و البته مخالفان نیز معتقد بودند این لوایح، مشکلی از مشکلات مردم را حل نمی‌کند و نباید به ‌دنبال اضافه‌کردن اختیارات رئیس‌جمهور بود.‌

حالا اما باز هم انگار تاریخ تکرار می‌شود و باز هم رئیس‌جمهوری دیگر از کمبود اختیاراتش حرف می‌زند و بار دیگر بحث‌ها و نظرها در مجلس، شورای نگهبان و احزاب و گروه‌های سیاسی بر سر اصلاح‌ قانون انتخابات داغ است و جالب‌تر از اینها روایتی است که اخیرا علی صوفی، فعال سیاسی اصلاح‌طلب در گفت‌وگو با «برنا» درباره موضع محمد یزدی در مواجهه با لوایح دوقلو بیان کرده است: «فردی از مرحوم آیت‌الله یزدی خاطره جالبی نقل کرده است. وقتی آقای خاتمی لایحه دوقلوی انتخابات را به مجلس داده است یکی از موارد این بوده که ببینند مسئول اجرای قانون اساسی در کشور که در قانون اساسی، رئیس‌جمهور نام برده شده شامل همه اصول قانون اساسی می‌شود یا نه؟ آقای یزدی گفته است که مسلم است که شامل همه‌چیز می‌شود. گفته‌اند پس چرا شما در شورای نگهبان رد کرده‌اید، گفته‌اند چون آقای خاتمی سؤال کرد!».

ماجرای لوایح دوقلو و حواشی آن

سیدمحمد خاتمی پس از انتخاب مجددش به‌عنوان رئیس‌جمهور در ۱۸ خرداد سال ۱۳۸۰، لایحه‌ای که سال‌ها پیش، یعنی در تاریخ ۲۲ آبان ۶۵، با عنوان اصلاح مواد فصل دوم قانون تعیین حدود وظایف و اختیارات ریاست‌جمهوری اسلامی ایران آماده شده بود، بار دیگر مورد توجه قرار گرفت و دولت در تاریخ ۲۷ شهریور ۸۱ آن را تصویب کرد. خاتمی تصمیم گرفت تمام تلاش خود را برای تبیین اختیارات رئیس‌جمهور و اصلاح قانون انتخابات در قالب دو لایحه به کار بگیرد؛ لوایحی که بعدها لوایح دوگانه رئیس‌جمهور و مهم‌ترین لوایح دولت خاتمی در هشت سال ریاست‌جمهوری او لقب گرفت. دولت این لوایح را تقدیم مجلس کرد، اما بین مجلس و شورای نگهبان بارها در رفت‌وآمد گرفتار شد.

خاتمی پیش از رد مجدد لوایح در شورای نگهبان گفته بود لایحه تبیین اختیارات «اگر تصویب نشود، دیگر رئیس‌جمهوری آن نیست که قانون اساسی معین کرده و مردم باید بدانند که به چه رئیس‌جمهوری رأی می‌دهند و چه توقعی از او دارند»؛ خاتمی لایحه اصلاح قانون انتخابات را نیز برای تثبیت حق مسلم مردم و اهتمام به آن می‌دانست، آن‌طوری‌که مورد نظر جمهوری اسلامی ایران است.
"""
# A sample  of political newsfrom 27 December https://www.hamshahrionline.ir/news/575438/%D8%A7%D8%AE%D8%AA%DB%8C%D8%A7%D8%B1%D8%A7%D8%AA-%D8%B1%D8%A6%DB%8C%D8%B3-%D8%AC%D9%85%D9%87%D9%88%D8%B1-%D8%A7%D8%B2-%D9%84%D9%88%D8%A7%DB%8C%D8%AD-%D8%AF%D9%88%D9%82%D9%84%D9%88%DB%8C-%D8%AE%D8%A7%D8%AA%D9%85%DB%8C-%D8%AA%D8%A7-%DA%AF%D9%84%D8%A7%DB%8C%D9%87-%D9%87%D8%A7%DB%8C-%D8%B1%D9%88%D8%AD%D8%A7%D9%86%DB%8C
# A sample  of social news  from 27 December https://www.hamshahrionline.ir/news/575642/%D9%88%D8%A7%DA%A9%D9%86%D8%B4-%D8%AA%D9%86%D8%AF-%D8%A7%D8%A8%D8%AA%DA%A9%D8%A7%D8%B1-%D8%A8%D9%87-%D9%85%D8%B4%D8%A7%D9%88%D8%B1-%D9%88%D8%B2%DB%8C%D8%B1-%D8%A8%D9%87%D8%AF%D8%A7%D8%B4%D8%AA-%D8%AE%D9%88%D8%AF%D8%AA%D8%A7%D9%86-%D8%AD%D8%A7%D8%B6%D8%B1%DB%8C%D8%AF-%D8%AF%D8%AE%D8%AA%D8%B1-%D8%AE%D8%B1%D8%AF%D8%B3%D8%A7%D9%84%D8%AA%D8%A7%D9%86
sample2 = """
معاون رئیس‌جمهوری در امور زنان و خانواده با تاکید بر اینکه «به هیچ عنوان به دنبال تعیین سن ازدواج یا افزایش سن ازدواج به بالای ۱۸ سال نیستیم» از موافقان کودک‌همسری پرسید که آیا حاضرند دخترکان خود را به عقد و ازدواج مردان سن بالا درآورند؟
معصومه ابتکار

به گزارش همشهری آنلاین به نقل از ایرنا، معصومه ابتکار معاون رئیس‌جمهوری در امور زنان و خانواده گفت: در فرهنگ ایرانی- اسلامی موضوع ازدواج سالم یکی از مسائل مهم است که پیمایش‌های صورت‌گرفته از میزان تمایل خانواده های ایرانی به امر ازدواج، تاییدکننده این موضوع است، چنانچه شاهدیم که شرایط کرونا و وضعیت کنونی هم مانع امر ازدواج نشده است.

وی ادامه داد: ازدواج در فرهنگ دینی هم بسیار مورد توجه قرار گرفته و آیات قرآن کریم تاکید بر این دارند که ازدواج در سن و شرایط مناسب باید صورت گیرد. ضمن اینکه در احادیث هم تاکید شده که دوره کودکی را از کودکان دریغ نکنید که یکی از روش‌های دریغ کردن دوره کودکی این است که آنها را زیر سن قانونی و کودکی وادار به ازدواج کنیم.

معاون رئیس جمهوری در امور زنان و خانواده درباره پیامدهای کودک همسری اظهار کرد: از جمله پیامدهای  ازدواج در دوره ای که کودک به سن رشدی که قرآن کریم بر آن تاکید دارد نرسیده، این است که هیچگونه اشراف و تشخیص نسبت به ازدواج ندارد، افزون بر اینکه از حقوق مدنی کافی همچون باز کردن حساب بانکی یا در راهروهای دادگاه به دنبال حق و حقوق خود رفتن برخوردار نیست.

وی یادآور شد: وقتی رشد فیزیولوژی و جسمی دختر اتفاق نیفتاده باشد، آسیب های بسیار زیادی از لحاظ بهداشتی خواهد دید که خطرناک است.

دراین‌باره ببینید؛ اظهارات جنجالی مشاور وزیر بهداشت درباره انتقادات به کودک‌ همسری: مزخرفات است

ابتکار گفت: خوشبختانه در حال حاضر قانون حمایت از اطفال و نوجوانان در موضوع حقوق کودک راهگشا و کمک کننده است، تصریح کرد: مباحثی هم روی موضوع سن ازدواج مطرح شده و موضع گیری و نگاه و فتاوی بزرگان و مراجع عالیقدر بر آن بسیار قابل توجه است. از جمله آیت الله مکارم شیرازی به صراحت عقد کودک زیر ۱۳ سال را باطل اعلام کردند. همچنین رهبر معظم انقلاب به صراحت به موضوع کودک همسری واکنش نشان داده و فرموده اند که واداشتن دختران کم سن و سال به ازدواج، حرکتی در جهت تضعیف زن و نادیده گرفتن حقوق اوست و قانون باید با آن مقابله کند و زنان نیز با آگاهی، هوشیاری و رشد و معرفت خود در مقابل این گونه تعدیات بایستند.

به گفته وی، آنچه معاونت هم بر آن تاکید دارد ازدواج در سن قانونی ۱۳ سال به بالا و پیشگیری از ۳۰ هزار ازدواج زیر سن قانونی و کودک همسری در سال است؛ شاید عنوان شود رقم آنچنانی نیست اما معتقدیم یک مورد کودک همسری هم زیان بار و اشتباه است.   

    کودک‌همسری بازیچه سیاسی شده است

ابتکار گفت: سیاست ما، تشویق جوانان به امر ازدواج در سن مناسب است، پیشنهاد و تاکید ما ممنوع شدن ازدواج زیر ۱۳ سال است؛ به این معنا که تبصره و هر راه یا مسیری که مجوز ازدواج زیر ۱۳ سال را می دهد حذف شود.

معاون رئیس جمهوری تاکید کرد: به هیچ عنوان به دنبال تعیین سن ازدواج یا افزایش سن ازدواج به بالای ۱۸ سال نیستیم، تصریح کرد: معتقدیم دختر اگر شرایط لازم برای ازدواج را داراست، این امر می تواند در سن بالای ۱۳ سال اتفاق بیافتد.

وی از موضع‌گیری مخالفان که اقدامات پیشگیری از کودک‌همسری را امنیتی و سیاسی می کنند، گلایه کرد و توضیح داد: فقط باید به نگاه مخالفان خندید و تاسف خورد که یک معضل واقعی جامعه که باید مسئولانه در قبال آن موضع‌گیری شود، به یک بازیچه سیاسی در دست عده‌ای برای کوبیدن عده‌ای دیگر تبدیل شده است.

ابتکار گفت: باید از مخالفان این موضوع پرسید که آیا حاضر هستید دخترکان خود را به عقد و ازدواج مردان سن بالا درآورید؟ باید از این افراد پرسید چطور یک کودک زیر سن قانونی نمی تواند حساب بانکی، حق رای و گواهینامه داشته باشد اما برای امر مهم ازدواج توانایی دارد؟  

او با تاکید بر اینکه کودک‌همسری دغدغه علما و مراجع و بسیاری از صاحبنظران فرهنگی و اجتماعی است که باید همه برای پیشگیری از آن تلاش کنیم، افزود: وجدان عمومی جامعه هم اجازه چنین موضوعی را نمی‌دهد. توجه و تاکید دولت هم این است که ازدواج بین ۱۳ تا ۱۵ زیر نظر خانواده و قاضی امکانپذیر باشد و ۱۳ سال به پایین کلا متوقف شود.
"""

# A sample of economic news from 27 December  https://www.hamshahrionline.ir/news/575516/%D9%87%D8%B4%D8%AF%D8%A7%D8%B1-%D8%B3%DB%8C%D8%A7%D8%B3%DB%8C-%D8%A8%D9%87-%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1-%D8%B3%DA%A9%D9%87-%D9%81%D9%84%D8%B2-%DA%AF%D8%B1%D8%A7%D9%86%D8%A8%D9%87%D8%A7%DB%8C-%D8%AF%D8%A7%D8%AE%D9%84%DB%8C-%D8%A8%D8%A7-%D8%AF%D9%84%D8%A7%D8%B1-%D8%AD%D8%B1%DA%A9%D8%AA-%D8%AE%D9%88%D8%A7%D9%87%D8%AF
sample3 = """
هشدار سیاسی به بازار سکه | فلز گرانبهای داخلی با دلار حرکت خواهد کرد؟


سکه برای اینکه با سرعت زیادی افزایشی شود، سه مانع را در مقابل خود می بیند.
سكه هوم پيج

به گزارش همشهری آنلاین به نقل از اقتصادنیوز، «وضعیت هشدار در بغداد به بالاترین سطح خود رسیده است». خبرهایی مشابه با این عنوان، از اواخر روز جمعه، به میزان زیادی در کانال های اطلاع رسانی معامله گران منتشر شد. طبیعتا هدف از انتشار وسیع این اخبار این بود که سطح نگرانی معامله گران بالا رود و خریدهای سکه و ارز افزایش پیدا کند.  

    آخرین قیمت طلا و انواع سکه در بازار | حباب سکه چقدر شد؟

با این حال، قیمت سکه برای اینکه با سرعت زیادی افزایشی شود، سه مانع را در مقابل خود می بیند. اولین مانع، حباب این فلز گران بهاست؛ فلز گران بهای داخلی در انتهای هفته گذشته حدود ۵۰۰ هزار تومان حباب داشت و در واقع نزدیک به ۵ درصد بالاتر از ارزش ذاتی خود معامله می شد.

دومین مانع برای قیمت سکه، افزایش فروش ها در نزدیکی محدوده ۱۲ میلیون و ۲۰۰ هزار تومانی است. به عبارت دیگر، ممکن است سکه در واکنش به اخبار و نگرانی های سیاسی حتی به بالای ۱۲ میلیون تومان برود، ولی برای عبور از مقاومت ۱۲ میلیون و ۲۰۰ هزار تومان دشواری های زیادی دارد.

    سکه وارد کانال ۱۲ میلیونی شد | جدیدترین قیمت طلا و انواع سکه در ۴ دیماه ۹۹

سومین مانع سکه، تعطیلی بازار طلای جهانی است؛ این مساله موجب می شود که سکه بیشتر از همیشه به روند دلار متکی باشد. اسکناس آمریکایی هم به طور خاص در چهار هفته اخیر، توان عبور از سطح ۲۶ هزار و ۳۰۰ تومان را نداشته است، در نتیجه برای بازیگران بازار سکه دشوار است که با تکیه بر متغیر دلار بخواهند خریدهای خود را بسیار شدت ببخشند.

به گفته برخی فعالان، ممکن است سکه در واکنش به نگرانی های سیاسی تا حدی افزایشی شود، ولی نمی توان گفت که این افزایش باعث ثبت رکوردهای جدید در بازار شود. اگر تنش ها در عراق ادامه پیدا نکند، حتی احتمال افت سکه نیز وجود خواهد داشت.
"""
# A sample of sports news from 27 December 
sample4 = """

نگرانی بزرگ محمود فکری؛ وضعیت مبهم سه ستاره استقلال برای دربی

۳ستاره آبی ها با توجه به اظهارنظر کادرپزشکی و صحبت‌هایی که امروز محمود فکری انجام داده به دیدار روز چهارشنبه ۱۰ دیماه با گل‌گهر سیرجان نخواهند رسید.
استقلال

به گزارش همشهری آنلاین اگرچه امروز دیاباته درتمرینات گروهی استقلال حاضر شد اما گفته می شود فکری در مورد این بازیکن ریسک نخواهد و او را برابر گل گهر به میدان نخواهد فرستاد تا مهاجم آبی ها در صورت رسیدن به آمادگی کامل مهیای دربی شود.. به جز دیاباته دو بازیکن دیگر اسقلال هم تقریبا همین شرایط را دارند.  داریوش شجاعیان و محمد نادری ۲ بازیکن مصدوم استقلال هستند که اگرچه در تمرینات حضور دارند اما هنوز شرایط بازی کردن را پیدا نکرده‌اند و مشخص نیست این امکان را چه زمانی به دست خواهند آورد.

۳ستاره آبی ها با توجه به اظهارنظر کادرپزشکی و صحبت‌هایی که امروز محمود فکری انجام داده به دیدار روز چهارشنبه ۱۰ دیماه با گل‌گهر سیرجان نخواهند رسید.
"""

In [303]:
samples = (sample1, sample2, sample3, sample4)
for i in samples:
    print(i)
    print('*******************')
    print('*******************')



به گزارش همشهریآنلاین به نقل از شرق،  «در بعضی جاها اختیار رئیس‌جمهور از اختیار یک شهروند عادی کمتر است... لوایح دوگانه حداقل‌هایی است که باید باشد... بدون رعایت روح لوایح، دیگر رئیس‌جمهور خیلی کاره‌ای نیست». این جملات سیدمحمد خاتمی در روزهایی بیان شد که لوایح دوگانه پیشنهادی‌اش بین شورای نگهبان و مجلس در رفت‌وآمد بود؛ لوایحی که به اعتقاد برخی از صاحب‌نظران برای اجرای قانون اساسی و رعایت حقوق ملت لازم و ضروری بود و البته مخالفان نیز معتقد بودند این لوایح، مشکلی از مشکلات مردم را حل نمی‌کند و نباید به ‌دنبال اضافه‌کردن اختیارات رئیس‌جمهور بود.‌

حالا اما باز هم انگار تاریخ تکرار می‌شود و باز هم رئیس‌جمهوری دیگر از کمبود اختیاراتش حرف می‌زند و بار دیگر بحث‌ها و نظرها در مجلس، شورای نگهبان و احزاب و گروه‌های سیاسی بر سر اصلاح‌ قانون انتخابات داغ است و جالب‌تر از اینها روایتی است که اخیرا علی صوفی، فعال سیاسی اصلاح‌طلب در گفت‌وگو با «برنا» درباره موضع محمد یزدی در مواجهه با لوایح دوقلو بیان کرده است: «فردی از مرحوم آیت‌الله یزدی خاطره جالبی نقل کرده است. وقتی آقای خاتمی لایحه دوقلوی انتخا

In [304]:
normalize = hazm.Normalizer()

In [305]:
norm_samples = [normalize.normalize(sample) for sample in samples]

In [306]:
print(norm_samples[0])


به گزارش همشهریآنلاین به نقل از شرق، «در بعضی جاها اختیار رئیس‌جمهور از اختیار یک شهروند عادی کمتر است … لوایح دوگانه حداقل‌هایی است که باید باشد … بدون رعایت روح لوایح، دیگر رئیس‌جمهور خیلی کاره‌ای نیست». این جملات سیدمحمد خاتمی در روزهایی بیان شد که لوایح دوگانه پیشنهادی‌اش بین شورای نگهبان و مجلس در رفت‌وآمد بود؛ لوایحی که به اعتقاد برخی از صاحب‌نظران برای اجرای قانون اساسی و رعایت حقوق ملت لازم و ضروری بود و البته مخالفان نیز معتقد بودند این لوایح، مشکلی از مشکلات مردم را حل نمی‌کند و نباید به ‌دنبال اضافه‌کردن اختیارات رئیس‌جمهور بود. ‌

حالا اما باز هم انگار تاریخ تکرار می‌شود و باز هم رئیس‌جمهوری دیگر از کمبود اختیاراتش حرف می‌زند و بار دیگر بحث‌ها و نظرها در مجلس، شورای نگهبان و احزاب و گروه‌های سیاسی بر سر اصلاح‌ قانون انتخابات داغ است و جالب‌تر از اینها روایتی است که اخیرا علی صوفی، فعال سیاسی اصلاح‌طلب در گفت‌وگو با «برنا» درباره موضع محمد یزدی در مواجهه با لوایح دوقلو بیان کرده است: «فردی از مرحوم آیت‌الله یزدی خاطره جالبی نقل کرده است. وقتی آقای خاتمی لایحه دوقلوی انتخابا

In [307]:
sample_tokens = [hazm.word_tokenize(sample) for sample in norm_samples]

In [308]:
sample_tokens

[['به',
  'گزارش',
  'همشهریآنلاین',
  'به',
  'نقل',
  'از',
  'شرق',
  '،',
  '«',
  'در',
  'بعضی',
  'جاها',
  'اختیار',
  'رئیس\u200cجمهور',
  'از',
  'اختیار',
  'یک',
  'شهروند',
  'عادی',
  'کمتر',
  'است',
  '…',
  'لوایح',
  'دوگانه',
  'حداقل\u200cهایی',
  'است',
  'که',
  'باید',
  'باشد',
  '…',
  'بدون',
  'رعایت',
  'روح',
  'لوایح',
  '،',
  'دیگر',
  'رئیس\u200cجمهور',
  'خیلی',
  'کاره\u200cای',
  'نیست',
  '»',
  '.',
  'این',
  'جملات',
  'سیدمحمد',
  'خاتمی',
  'در',
  'روزهایی',
  'بیان',
  'شد',
  'که',
  'لوایح',
  'دوگانه',
  'پیشنهادی\u200cاش',
  'بین',
  'شورای',
  'نگهبان',
  'و',
  'مجلس',
  'در',
  'رفت\u200cوآمد',
  'بود',
  '؛',
  'لوایحی',
  'که',
  'به',
  'اعتقاد',
  'برخی',
  'از',
  'صاحب\u200cنظران',
  'برای',
  'اجرای',
  'قانون',
  'اساسی',
  'و',
  'رعایت',
  'حقوق',
  'ملت',
  'لازم',
  'و',
  'ضروری',
  'بود',
  'و',
  'البته',
  'مخالفان',
  'نیز',
  'معتقد',
  'بودند',
  'این',
  'لوایح',
  '،',
  'مشکلی',
  'از',
  'مشکلات',
  'مردم',
  'را

In [309]:
for i in sample_tokens:
    print(len(i))

464
765
368
158


In [310]:
vec_sample = tfidf.transform(sample_tokens)

In [311]:
vec_sample

<4x22685 sparse matrix of type '<class 'numpy.float64'>'
	with 207 stored elements in Compressed Sparse Row format>

In [312]:
for vec in vec_sample:
    print(tfidf.inverse_transform(vec))

[array(['۸۱', '۶۵', '۱۳۸۰', 'یزدی', 'گفته_بود', 'گفته_است', 'گرفتار',
       'نگهبان', 'نظرها', 'موضع', 'مواجهه', 'معین', 'مشکلی', 'مسلم',
       'مرحوم', 'مخالفان', 'مجدد', 'ماجرای', 'لوایحی', 'لوایح', 'لقب',
       'لایحه', 'صوفی', 'شهریور', 'شهروند', 'سیدمحمد', 'روزهایی', 'روح',
       'روایتی', 'دوگانه', 'دوقلوی', 'دوقلو', 'داغ', 'خاطره', 'حواشی',
       'جملات', 'جاها', 'جالبی', 'توقعی', 'تقدیم', 'تثبیت', 'تبیین',
       'بعدها', 'برده', 'بدانند', 'ببینند', 'بارها', 'اهتمام', 'انگار',
       'اختیارات', 'احزاب', 'آبان'], dtype='<U21')]
[array(['گواهینامه', 'گلایه', 'کودکی', 'کوبیدن', 'کلا', 'کریم', 'چنانچه',
       'چطور', 'پیشگیری', 'پیامدهای', 'پرسید', 'وجدان', 'واداشتن',
       'وادار', 'هیچگونه', 'هوشیاری', 'همسری', 'هستید', 'نیفتاده',
       'نیستیم', 'نکنید', 'نرسیده', 'نادیده', 'مکارم', 'موضوعی', 'موضع',
       'موافقان', 'ممنوع', 'معنا', 'معضل', 'معصومه', 'معرفت', 'معتقدیم',
       'مشاور', 'مسیری', 'مسئولانه', 'مراجع', 'مدنی', 'مخالفان', 'مباحثی',
       'قرآن', 'قبال', '

In [313]:
label_encoder.inverse_transform(lr.predict(vec_sample))

array(['Politics', 'Miscellaneous', 'Economy', 'Sport'], dtype=object)

In [314]:
pred_classes(sample_tokens[0])

['Economy']  :  1.35 %
['Literature and Art']  :  0.389 %
['Miscellaneous']  :  9.73 %
['Natural Environment']  :  0.0699 %
['Politics']  :  87.3 %
['Science and Culture']  :  0.554 %
['Social']  :  0.384 %
['Sport']  :  0.187 %
['Tourism']  :  0.0434 %


In [315]:
pred_classes(sample_tokens[1])

['Economy']  :  0.501 %
['Literature and Art']  :  0.243 %
['Miscellaneous']  :  62.5 %
['Natural Environment']  :  0.0567 %
['Politics']  :  1.55 %
['Science and Culture']  :  0.364 %
['Social']  :  34.7 %
['Sport']  :  0.106 %
['Tourism']  :  0.0326 %


In [316]:
pred_classes(sample_tokens[2])

['Economy']  :  96.8 %
['Literature and Art']  :  0.314 %
['Miscellaneous']  :  1.5 %
['Natural Environment']  :  0.0708 %
['Politics']  :  0.607 %
['Science and Culture']  :  0.283 %
['Social']  :  0.23 %
['Sport']  :  0.141 %
['Tourism']  :  0.0297 %


In [317]:
pred_classes(sample_tokens[3])

['Economy']  :  7.29 %
['Literature and Art']  :  3.8 %
['Miscellaneous']  :  28.4 %
['Natural Environment']  :  0.729 %
['Politics']  :  7.15 %
['Science and Culture']  :  7.79 %
['Social']  :  3.19 %
['Sport']  :  41.0 %
['Tourism']  :  0.577 %


In [277]:
LogisticRegression?

In [285]:
%time lr_sparse = LogisticRegression(max_iter=10, penalty='l1', solver='saga', verbose=True)

CPU times: user 17 µs, sys: 0 ns, total: 17 µs
Wall time: 22.4 µs


In [287]:
%time lr_sparse.fit(X_train, label_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


max_iter reached after 15 seconds
max_iter reached after 10 seconds
max_iter reached after 24 seconds
max_iter reached after 5 seconds
max_iter reached after 14 seconds
max_iter reached after 14 seconds
max_iter reached after 12 seconds
max_iter reached after 7 seconds
max_iter reached after 4 seconds
CPU times: user 1min 44s, sys: 135 ms, total: 1min 44s
Wall time: 1min 45s


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:  1.8min finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10,
                   multi_class='warn', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=True,
                   warm_start=False)

In [288]:
import gc;gc.collect()

176

In [290]:
lr_sparse.score(X_train, label_train)

0.8233370642788616

In [292]:
lr_sparse.sparsify()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10,
                   multi_class='warn', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=True,
                   warm_start=False)

In [293]:
lr_sparse.coef_

<9x22685 sparse matrix of type '<class 'numpy.float64'>'
	with 22825 stored elements in Compressed Sparse Row format>

In [297]:
lr.sparsify()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=True,
                   warm_start=False)

In [298]:
lr.coef_

<9x22685 sparse matrix of type '<class 'numpy.float64'>'
	with 204165 stored elements in Compressed Sparse Row format>

In [300]:
eval_results(label_test, lr_sparse.predict(X_test))

                     precision    recall  f1-score   support

            Economy       0.85      0.82      0.83      5892
 Literature and Art       0.72      0.58      0.64      1621
      Miscellaneous       0.78      0.89      0.83     19272
Natural Environment       0.52      0.11      0.18       233
           Politics       0.80      0.70      0.75      4884
Science and Culture       0.69      0.56      0.62      3383
             Social       0.71      0.51      0.60      2373
              Sport       0.97      0.95      0.96      3925
            Tourism       0.65      0.27      0.38       111

           accuracy                           0.80     41694
          macro avg       0.74      0.60      0.64     41694
       weighted avg       0.79      0.80      0.79     41694

[[ 4802     1   895     0   116    40    21     9     8]
 [   10   943   559     0     4    76    23     6     0]
 [  507   257 17106    14   531   538   250    64     5]
 [    8     3   178    25     1  

In [319]:
%time lr_sparse.predict_proba(vec_sample[3])

CPU times: user 3.74 ms, sys: 0 ns, total: 3.74 ms
Wall time: 2.75 ms


array([[0.03855363, 0.01661163, 0.14945471, 0.00181199, 0.0478397 ,
        0.05403346, 0.00705236, 0.68356312, 0.00107939]])

In [323]:
%time lr.predict_proba(vec_sample[3])

CPU times: user 2.52 ms, sys: 15 µs, total: 2.54 ms
Wall time: 1.9 ms


array([[0.07287228, 0.03796737, 0.28443607, 0.00729043, 0.07154442,
        0.07788938, 0.03194072, 0.41029204, 0.00576728]])

## Doc2vec Model 

In [13]:
del X_train, X_test

NameError: name 'X_train' is not defined

In [14]:
import gc;gc.collect()

28

In [15]:
from  gensim.models.doc2vec import Doc2Vec, TaggedDocument

In [16]:
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(tokens_train)]

In [17]:
def discard_freq(word, count, min_count):
    if count <= 1000:
        return gensim.utils.RULE_KEEP
    return gensim.utils.RULE_DISCARD

In [18]:
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [19]:
documents_test = [TaggedDocument(doc, [str(label)])
                 for label, doc in zip(label_test, tokens_test)]

In [20]:
%%time
doc2vec_1 = Doc2Vec(documents=documents,
        dm=0,
        vector_size=300,
        min_count=100,
        negative=5,
#         trim_rule=discard_freq,
        verbose=True,
        workers=4
       )

2020-12-27 05:00:26,179 : INFO : collecting all words and their counts
2020-12-27 05:00:26,182 : INFO : PROGRESS: at example #0, processed 0 words (0/s), 0 word types, 0 tags
2020-12-27 05:00:27,009 : INFO : PROGRESS: at example #10000, processed 3947153 words (4782120/s), 105112 word types, 10000 tags
2020-12-27 05:00:27,860 : INFO : PROGRESS: at example #20000, processed 7954995 words (4711571/s), 159336 word types, 20000 tags
2020-12-27 05:00:28,685 : INFO : PROGRESS: at example #30000, processed 11951836 words (4849223/s), 204660 word types, 30000 tags
2020-12-27 05:00:29,514 : INFO : PROGRESS: at example #40000, processed 15886072 words (4752122/s), 244068 word types, 40000 tags
2020-12-27 05:00:30,387 : INFO : PROGRESS: at example #50000, processed 19932242 words (4637887/s), 279089 word types, 50000 tags
2020-12-27 05:00:31,324 : INFO : PROGRESS: at example #60000, processed 23892239 words (4230051/s), 310832 word types, 60000 tags
2020-12-27 05:00:32,237 : INFO : PROGRESS: at e

2020-12-27 05:01:59,282 : INFO : EPOCH 1 - PROGRESS: at 68.93% examples, 512413 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:02:00,289 : INFO : EPOCH 1 - PROGRESS: at 70.76% examples, 515496 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:02:01,294 : INFO : EPOCH 1 - PROGRESS: at 72.47% examples, 518240 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:02:02,299 : INFO : EPOCH 1 - PROGRESS: at 74.00% examples, 519413 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:02:03,300 : INFO : EPOCH 1 - PROGRESS: at 75.72% examples, 521803 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:02:04,303 : INFO : EPOCH 1 - PROGRESS: at 77.53% examples, 525028 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:02:05,307 : INFO : EPOCH 1 - PROGRESS: at 79.20% examples, 526719 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:02:06,314 : INFO : EPOCH 1 - PROGRESS: at 81.19% examples, 530513 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:02:07,322 : INFO : EPOCH 1 - PROGRESS: at 83.00% examples, 532735 words/s, in_qsiz

2020-12-27 05:03:09,585 : INFO : EPOCH 2 - PROGRESS: at 72.83% examples, 530218 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:03:10,597 : INFO : EPOCH 2 - PROGRESS: at 74.50% examples, 532059 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:03:11,609 : INFO : EPOCH 2 - PROGRESS: at 75.95% examples, 532045 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:03:12,623 : INFO : EPOCH 2 - PROGRESS: at 77.42% examples, 532757 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:03:13,641 : INFO : EPOCH 2 - PROGRESS: at 79.08% examples, 534164 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:03:14,656 : INFO : EPOCH 2 - PROGRESS: at 80.88% examples, 536525 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:03:15,693 : INFO : EPOCH 2 - PROGRESS: at 82.08% examples, 534632 words/s, in_qsize 6, out_qsize 1
2020-12-27 05:03:16,700 : INFO : EPOCH 2 - PROGRESS: at 83.47% examples, 534107 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:03:17,716 : INFO : EPOCH 2 - PROGRESS: at 84.64% examples, 532453 words/s, in_qsiz

2020-12-27 05:04:20,234 : INFO : EPOCH 3 - PROGRESS: at 78.92% examples, 588814 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:04:21,249 : INFO : EPOCH 3 - PROGRESS: at 80.76% examples, 590748 words/s, in_qsize 8, out_qsize 1
2020-12-27 05:04:22,260 : INFO : EPOCH 3 - PROGRESS: at 82.64% examples, 592523 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:04:23,265 : INFO : EPOCH 3 - PROGRESS: at 84.31% examples, 592946 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:04:24,285 : INFO : EPOCH 3 - PROGRESS: at 86.06% examples, 594120 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:04:25,301 : INFO : EPOCH 3 - PROGRESS: at 87.67% examples, 594193 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:04:26,305 : INFO : EPOCH 3 - PROGRESS: at 89.38% examples, 595145 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:04:27,316 : INFO : EPOCH 3 - PROGRESS: at 91.24% examples, 596472 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:04:28,328 : INFO : EPOCH 3 - PROGRESS: at 93.17% examples, 598308 words/s, in_qsiz

2020-12-27 05:05:30,473 : INFO : EPOCH 4 - PROGRESS: at 97.78% examples, 627914 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:05:31,477 : INFO : EPOCH 4 - PROGRESS: at 99.49% examples, 627721 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:05:31,768 : INFO : worker thread finished; awaiting finish of 3 more threads
2020-12-27 05:05:31,780 : INFO : worker thread finished; awaiting finish of 2 more threads
2020-12-27 05:05:31,785 : INFO : worker thread finished; awaiting finish of 1 more threads
2020-12-27 05:05:31,786 : INFO : worker thread finished; awaiting finish of 0 more threads
2020-12-27 05:05:31,787 : INFO : EPOCH - 4 : training on 49762270 raw words (37577402 effective words) took 59.9s, 627666 effective words/s
2020-12-27 05:05:32,797 : INFO : EPOCH 5 - PROGRESS: at 1.83% examples, 685818 words/s, in_qsize 8, out_qsize 0
2020-12-27 05:05:33,810 : INFO : EPOCH 5 - PROGRESS: at 3.59% examples, 675043 words/s, in_qsize 7, out_qsize 0
2020-12-27 05:05:34,810 : INFO : EPOCH 5 - PRO

CPU times: user 14min 21s, sys: 11.9 s, total: 14min 33s
Wall time: 6min 5s


In [334]:
from collections import Counter
def reinfer_ranking(d2v):
    ranks = []
    for i in range(len(documents[:100])):
        inferred_vector = d2v.infer_vector(documents[i].words, steps=20)
        sims = d2v.docvecs.most_similar([inferred_vector],
                                        topn=10)
        try:
            rank = [docid for docid, sim in sims].index(i)
        except ValueError:
            rank = None
        ranks.append(rank)
    counts = Counter(ranks)
    counts.pop(None)
    return sorted(counts.items())

In [335]:
reinfer_ranking(doc2vec_1)

[(0, 98)]

#### Nearest neighbors of samples

In [350]:
def similar_docs(d2v, words):
    inferred = d2v.infer_vector(words, steps=20)
    sims = d2v.docvecs.most_similar([inferred], topn=3)
    return list(map(lambda x: x[0], sims)), list(map(lambda x: x[1], sims))

In [370]:
def show_samples_nns(d2v):
    for sample in sample_tokens:
        sims_sample = similar_docs(d2v, sample)
        print("======================")
        print("Sample one")
        print(sample[:150])
        print("======================")
        print("nears")
        for i in range(3):
            print(documents[sims_sample[0][i]].words[:150])
    print("***********************")


In [369]:
show_samples_nns(doc2vec_1)

Sample one
['به', 'گزارش', 'همشهریآنلاین', 'به', 'نقل', 'از', 'شرق', '،', '«', 'در', 'بعضی', 'جاها', 'اختیار', 'رئیس\u200cجمهور', 'از', 'اختیار', 'یک', 'شهروند', 'عادی', 'کمتر', 'است', '…', 'لوایح', 'دوگانه', 'حداقل\u200cهایی', 'است', 'که', 'باید', 'باشد', '…', 'بدون', 'رعایت', 'روح', 'لوایح', '،', 'دیگر', 'رئیس\u200cجمهور', 'خیلی', 'کاره\u200cای', 'نیست', '»', '.', 'این', 'جملات', 'سیدمحمد', 'خاتمی', 'در', 'روزهایی', 'بیان', 'شد', 'که', 'لوایح', 'دوگانه', 'پیشنهادی\u200cاش', 'بین', 'شورای', 'نگهبان', 'و', 'مجلس', 'در', 'رفت\u200cوآمد', 'بود', '؛', 'لوایحی', 'که', 'به', 'اعتقاد', 'برخی', 'از', 'صاحب\u200cنظران', 'برای', 'اجرای', 'قانون', 'اساسی', 'و', 'رعایت', 'حقوق', 'ملت', 'لازم', 'و', 'ضروری', 'بود', 'و', 'البته', 'مخالفان', 'نیز', 'معتقد', 'بودند', 'این', 'لوایح', '،', 'مشکلی', 'از', 'مشکلات', 'مردم', 'را', 'حل', 'نمی\u200cکند', 'و', 'نباید', 'به', '\u200cدنبال', 'اضافه\u200cکردن', 'اختیارات', 'رئیس\u200cجمهور', 'بود', '.', '\u200c', 'حالا', 'اما', 'باز', 'هم', 'انگار', 'تاریخ', 'ت

### Classificaiton of Doc2vec

In [21]:
def make_test(d2v):
    X_test = np.array(list(d2v.infer_vector(doc.words, epochs=5)
                for doc in tqdm(documents_test)))
    return X_test

In [22]:
doc2vec_1.infer

AttributeError: 'Doc2Vec' object has no attribute 'infer'

In [23]:
X_test = make_test(doc2vec_1)

100%|██████████| 41694/41694 [02:56<00:00, 236.36it/s]


In [373]:
X_test

array(<generator object make_test.<locals>.<genexpr> at 0x7f7a99bd8a50>,
      dtype=object)

In [ ]:
X_train = np.array(list(doc2vec_1.docvecs.doctag_syn0

In [24]:
X_train = doc2vec_1.docvecs.doctag_syn0.copy()

#### lr model 

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
LogisticRegression?

In [32]:
lr = LogisticRegression(max_iter=40, tol=0.009, solver='sag', verbose=True,n_jobs=-1)

In [33]:
lr.fit(X_train, label_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   9 out of   9 | elapsed:  2.5min finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=40,
                   multi_class='warn', n_jobs=-1, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.009,
                   verbose=True, warm_start=False)

In [34]:
lr.score(X_train, label_train)

0.7837384074192517

In [35]:
eval_results(label_test, lr.predict(X_test))

                     precision    recall  f1-score   support

            Economy       0.82      0.82      0.82      5892
 Literature and Art       0.63      0.54      0.58      1621
      Miscellaneous       0.78      0.84      0.81     19272
Natural Environment       0.47      0.24      0.32       233
           Politics       0.72      0.71      0.71      4884
Science and Culture       0.64      0.55      0.59      3383
             Social       0.56      0.50      0.53      2373
              Sport       0.97      0.97      0.97      3925
            Tourism       0.77      0.40      0.52       111

           accuracy                           0.77     41694
          macro avg       0.71      0.62      0.65     41694
       weighted avg       0.77      0.77      0.77     41694

[[ 4843     2   801     2   125    62    43     6     8]
 [   14   878   551     1    16   106    49     5     1]
 [  653   351 16095    45   937   609   505    74     3]
 [   12     0   140    56     0  

#### MLP

In [36]:
import itertools
import os

# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelBinarizer, LabelEncoder
from sklearn.metrics import confusion_matrix

from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.preprocessing import text, sequence
from keras import utils
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(restore_best_weights=True, patience=25, 
                              min_delta=.001)


Using TensorFlow backend.


In [37]:
batch_size = 1000
epochs = 100
# encoder = LabelEncoder()
# encoder.fit(list(range(11)))
# y_train = encoder.transform(label_train)
# y_test = encoder.transform(label_test)
label_train_cat = utils.to_categorical(label_train, 9)
label_test_cat = utils.to_categorical(label_test, 9)
# Build the model
model = Sequential()
model.add(Dense(150, input_shape=(X_test.shape[1],)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(50, input_shape=(X_test.shape[1],)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(9))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='nadam',
              metrics=['accuracy'])


2020-12-27 05:18:38,448 : WARNING : From /home/fazel/anaconda3/envs/nlp_thesis/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2020-12-27 05:18:38,474 : WARNING : From /home/fazel/anaconda3/envs/nlp_thesis/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2020-12-27 05:18:38,481 : WARNING : From /home/fazel/anaconda3/envs/nlp_thesis/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

2020-12-27 05:18:38,507 : WARNING : From /home/fazel/anaconda3/envs/nlp_thesis/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

2020-12-27 05:18:38,519 : WARNING 

In [39]:
import keras

In [40]:
keras.backend.tensorflow_backend._get_available_gpust()

['/job:localhost/replica:0/task:0/device:GPU:0']

In [41]:
model.fit(X_train, label_train_cat,
          batch_size=batch_size,
          epochs=epochs,
          callbacks=[early_stopping],
          validation_split=0.1,
         )

Train on 112572 samples, validate on 12508 samples
Epoch 1/100
112572/112572 [==============================] - 2s 21us/step - loss: 0.9127 - acc: 0.6921 - val_loss: 0.6055 - val_acc: 0.7905
Epoch 2/100
112572/112572 [==============================] - 1s 11us/step - loss: 0.6817 - acc: 0.7681 - val_loss: 0.5436 - val_acc: 0.8112
Epoch 3/100
112572/112572 [==============================] - 1s 10us/step - loss: 0.6341 - acc: 0.7848 - val_loss: 0.5170 - val_acc: 0.8192
Epoch 4/100
112572/112572 [==============================] - 1s 10us/step - loss: 0.6055 - acc: 0.7946 - val_loss: 0.5068 - val_acc: 0.8232
Epoch 5/100
112572/112572 [==============================] - 1s 10us/step - loss: 0.5909 - acc: 0.8011 - val_loss: 0.4965 - val_acc: 0.8295
Epoch 6/100
112572/112572 [==============================] - 1s 11us/step - loss: 0.5727 - acc: 0.8057 - val_loss: 0.4868 - val_acc: 0.8305
Epoch 7/100
112572/112572 [==============================] - 1s 10us/step - loss: 0.5651 - acc: 0.8099 - val_

Epoch 59/100
112572/112572 [==============================] - 1s 13us/step - loss: 0.4791 - acc: 0.8375 - val_loss: 0.4567 - val_acc: 0.8451
Epoch 60/100
112572/112572 [==============================] - 1s 11us/step - loss: 0.4788 - acc: 0.8376 - val_loss: 0.4554 - val_acc: 0.8427
Epoch 61/100
112572/112572 [==============================] - 1s 12us/step - loss: 0.4767 - acc: 0.8375 - val_loss: 0.4554 - val_acc: 0.8451
Epoch 62/100
112572/112572 [==============================] - 1s 12us/step - loss: 0.4775 - acc: 0.8381 - val_loss: 0.4550 - val_acc: 0.8421
Epoch 63/100
112572/112572 [==============================] - 1s 12us/step - loss: 0.4794 - acc: 0.8384 - val_loss: 0.4525 - val_acc: 0.8443
Epoch 64/100
112572/112572 [==============================] - 1s 13us/step - loss: 0.4778 - acc: 0.8379 - val_loss: 0.4535 - val_acc: 0.8414
Epoch 65/100
112572/112572 [==============================] - 1s 12us/step - loss: 0.4754 - acc: 0.8375 - val_loss: 0.4533 - val_acc: 0.8416
Epoch 66/100


In [42]:
model.save?

In [43]:
model.save("mlp1.h5")

In [45]:
doc2vec_1.save("doc2vec_1.save")

2020-12-27 05:38:09,170 : INFO : saving Doc2Vec object under doc2vec_1.save, separately None
2020-12-27 05:38:09,171 : INFO : storing np array 'vectors_docs' to doc2vec_1.save.docvecs.vectors_docs.npy
2020-12-27 05:38:09,797 : INFO : saved doc2vec_1.save


In [46]:
X_pred = model.predict(X_test)
y_pred = np.argmax(X_pred, axis=1)
eval_results(label_test, y_pred)

                     precision    recall  f1-score   support

            Economy       0.88      0.86      0.87      5892
 Literature and Art       0.64      0.70      0.67      1621
      Miscellaneous       0.85      0.86      0.86     19272
Natural Environment       0.50      0.07      0.13       233
           Politics       0.81      0.77      0.79      4884
Science and Culture       0.72      0.72      0.72      3383
             Social       0.65      0.69      0.67      2373
              Sport       0.96      0.98      0.97      3925
            Tourism       0.79      0.33      0.47       111

           accuracy                           0.83     41694
          macro avg       0.76      0.67      0.68     41694
       weighted avg       0.83      0.83      0.83     41694

[[ 5069     4   579     0   119    46    58    10     7]
 [    6  1141   350     0     1    85    31     7     0]
 [  403   431 16642     8   570   595   527    94     2]
 [    3     1   173    17     0  

#### MLP for tfidf 

In [50]:

X_test_tfidf = tfidf.transform(tqdm(tokens_test))

100%|██████████| 41694/41694 [00:07<00:00, 5828.09it/s]


In [53]:
batch_size = 1000
epochs = 100
# encoder = LabelEncoder()
# encoder.fit(list(range(11)))
# y_train = encoder.transform(label_train)
# y_test = encoder.transform(label_test)
label_train_cat = utils.to_categorical(label_train, 9)
label_test_cat = utils.to_categorical(label_test, 9)
# Build the model
model = Sequential()
model.add(Dense(150, input_shape=(X_test_tfidf.shape[1],)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(50, input_shape=(X_test_tfidf.shape[1],)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(9))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='nadam',
              metrics=['accuracy'])


import keras



model.fit(X_train, label_train_cat,
          batch_size=batch_size,
          epochs=epochs,
          callbacks=[early_stopping],
          validation_split=0.1,
         )

Train on 112572 samples, validate on 12508 samples
Epoch 1/100
112572/112572 [==============================] - 30s 269us/step - loss: 1.0712 - acc: 0.6662 - val_loss: 0.5943 - val_acc: 0.8007
Epoch 2/100
112572/112572 [==============================] - 30s 266us/step - loss: 0.6027 - acc: 0.8046 - val_loss: 0.5638 - val_acc: 0.8098
Epoch 3/100
112572/112572 [==============================] - 29s 260us/step - loss: 0.4963 - acc: 0.8397 - val_loss: 0.5712 - val_acc: 0.8046
Epoch 4/100
112572/112572 [==============================] - 31s 274us/step - loss: 0.4195 - acc: 0.8642 - val_loss: 0.5925 - val_acc: 0.8007
Epoch 5/100
112572/112572 [==============================] - 32s 286us/step - loss: 0.3552 - acc: 0.8851 - val_loss: 0.6340 - val_acc: 0.7982
Epoch 6/100
112572/112572 [==============================] - 33s 295us/step - loss: 0.3036 - acc: 0.9015 - val_loss: 0.6906 - val_acc: 0.7976
Epoch 7/100
112572/112572 [==============================] - 33s 293us/step - loss: 0.2586 - acc:

KeyboardInterrupt: 

In [54]:
X_pred = model.predict(X_test_tfidf)
y_pred = np.argmax(X_pred, axis=1)
eval_results(label_test, y_pred)

                     precision    recall  f1-score   support

            Economy       0.84      0.83      0.83      5892
 Literature and Art       0.67      0.63      0.65      1621
      Miscellaneous       0.80      0.84      0.82     19272
Natural Environment       0.45      0.22      0.30       233
           Politics       0.74      0.73      0.73      4884
Science and Culture       0.65      0.61      0.63      3383
             Social       0.62      0.57      0.60      2373
              Sport       0.98      0.96      0.97      3925
            Tourism       0.74      0.29      0.42       111

           accuracy                           0.79     41694
          macro avg       0.72      0.63      0.66     41694
       weighted avg       0.79      0.79      0.79     41694

[[ 4880     5   743     0   164    52    37     5     6]
 [    6  1021   466     0     4    92    29     3     0]
 [  595   354 16178    42   826   745   467    63     2]
 [    7     1   143    52     0  